In [1]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/Github/

Mounted at /content/drive
/content/drive/MyDrive/Github

In [ ]:
!git clone https://<<your_github_token>>@github.com/<<your_github_username>>/questions-with-SQL

Cloning into 'questions-with-SQL'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 29 (delta 9), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (29/29), 724.79 KiB | 5.89 MiB/s, done.
Resolving deltas: 100% (9/9), done.

In [2]:
%cd questions-with-SQL

/content/drive/MyDrive/Github/questions-with-SQL

# Answering Business Questions Using SQL

Use SQL to answer business questions using information about a fictional digital music shop. The Chinook database contains information about the artists, songs, and albums from the music shop, as well as data on the shop's employees, customers, and the customers' purchases.

The goal is to find answers and provide recommendations on the following:

* Which music genres sell the most tracks in the USA?
* What is the sales performance of the shop's employees?
* Which countries have the potential for growth?
* What percentage of purchases are whole albums versus individual tracks?
* Which artist is used in most playlists?
* How many tracks have been purchased versus not purchased?

## Creating Helper Functions

Use the helper functions

`run_query()` to quickly read SQL queries into DataFrames


`show_tables()` to return a list of all tables and views of the Chinook database, respectively.

In [5]:
import sqlite3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
%matplotlib inline

def run_query(q):
    with sqlite3.connect('chinook.db') as conn:
        return pd.read_sql(q, conn)

def show_tables():
    q = '''
    SELECT
        name

    FROM sqlite_master
    WHERE type in ("table", "view");
    '''
    return run_query(q)

show_tables()

              name
0            album
1           artist
2         customer
3         employee
4            genre
5          invoice
6     invoice_line
7       media_type
8         playlist
9   playlist_track
10           track

The Chinook database contains 11 tables of data.  The tables are related according to the database schema shown below.

![Chinook Schema](https://github.com/orcascope/questions-with-SQL/blob/master/chinook-schema.jpg?raw=1)

1. Top 3 customer states in terms of  invoice total.
2. Get just the Top 5th (not top 5) customer state in terms of number of distinct customers.
3. Find the top Selling Music Genres in the USA

## Analyzing Employee Sales Performance
1. Find the total_sales made by each employee. Print a report of emp_name, hire_date, country and total sales.

## Analyzing Sales by Country
Find total sales and total count of customers by country. Also find average sales by customer and average order value in each country.

Average sales by customer is Total Sales/Total num of customers
Average order value is Total Sales/Total num of invoices.

In [ ]:
# q3= '''
# '''

# run_query(q3)

## Purchases of Whole Albums Versus Individual Tracks
1. Find all the albums purchased in each of the invoice. (Customer purchased tracks, but the track belong to an album)

2. Find the count of albums which were purchased in full. i.e all tracks were purchased in the same sale invoice, rather than just 1 or 2 tracks,

In [ ]:
#

## Artist Mostly Used in Playlists
1. Which artist is more popular in the playlists ?
i.e Playlists are collection of tracks that were performed by Artists. Find which artist's tracks dominate the playlists

In [ ]:
#

## Purchased versus Unpurchased Tracks
1. Of the total tracks present in the albums,how many were purchased atleast once, and how many were never purchased.

In [ ]:
#

And or Not

In [27]:
q= """
select state, count(*)
from (select *
from customer
where state = 'CA' OR NOT state = 'TX'
) t
group by state """

run_query(q)

     state  count(*)
0       AB         1
1       AZ         1
2       BC         1
3       CA         3
4       DF         1
5   Dublin         1
6       FL         1
7       IL         1
8       MA         1
9       MB         1
10      NS         1
11     NSW         1
12      NT         1
13      NV         1
14      NY         1
15      ON         2
16      QC         1
17      RJ         1
18      RM         1
19      SP         3
20      UT         1
21      VV         1
22      WA         1
23      WI         1

In [64]:
q= """
select count(*)
from employee e left join customer c on c.support_rep_id = e.employee_id

"""

# q= "select * from customer c where c.support_rep_id = 0"

run_query(q)

   count(*)
0        64